### PR TITLE
Add OneSwapIndexUnsort etc.

### PR DESCRIPTION
**Pull request by nikolashn**
Rename Unsort to BasicUnsort.
Add OneSwapIndexUnsort, a more efficient unsorting algorithm than the basic one.
Permit the user to choose between the unsorting algorithm to be used in unsort.go:main.
Add the -func flag to unsort_test.go, which can be used to specify a particular unsorting algorithm

### CODE REVIEW

**Comment by 0x1a8510f2** [comment]
Thanks for the changes. One thing: we need to test both functions, not either, so instead of selecting a function in the test file, we'll need to always run tests for both. This means writing a second test function for the new unsort. LGTM otherwise!

**Comment by nikolashn** [comment]
Is it alright if I change the tests to benchmarks?

**Comment by 0x1a8510f2** [comment]
You can add benchmarks by all means, but we still need some tests, unless your benchmarks also ensure the arrays are unsorted well, thereby effectively also being tests.

**Comment by nikolashn** [comment]
Any issues with this?

**Comment by 0x1a8510f2** [comment]
As discussed in person :D

**Comment by 0x1a8510f2** [comment]
LGTM!

**Pull request merged**
